[build]
  command = "python3.11 -m pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11.0"

[context.production]
  command = "python app.py"

[context.production.environment]
  FLASK_ENV = "production"
  FLASK_APP = "app.py"
  PORT = "5001"

[dev]
  command = "python app.py"
  targetPort = 5001

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 